### ISSUE TITLE
Why you're link is a redirect to Avira???

### ISSUE THREAD

**Issue by katastrophe92** [martinet101/SomePythonThings-Zip-Manager#3]
![20-08-38 26February2023 x](https://user-images.githubusercontent.com/103950507/221433440-0af6dba2-ecc3-4e24-aac2-7acefcde5c75.gif)

**Comment by marticliment** [comment]
This project is not maintained anymore, and the domain `www.somepythonthings.tk` got stolen.

You can still, obiously, use the application if it is useful for you
